spring:
  application:
    name: product
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


message:
  exchange: market
  queue:
    product: market.product
    payment: market.payment
    err:
      product: market.err.product
      order: market.err.order
  err:
    exchange: market.err

